const TOOLS=[
{id:'gutter',label:'Gutter',short:'G',needsFeet:true,billable:1,color:'#2563eb'},
{id:'downspout',label:'Downspout',short:'DS',needsFeet:true,billable:1,color:'#059669'},
{id:'insideMiter',label:'Inside Miter',short:'IM',billable:3,color:'#dc2626'},
{id:'outsideMiter',label:'Outside Miter',short:'OM',billable:3,color:'#ea580c'},
{id:'outlet',label:'Outlet',short:'O',billable:1,color:'#4b5563'},
{id:'endCapPair',label:'End Cap Pair',short:'EC',billable:1,color:'#ca8a04'},
{id:'aElbow',label:'A Elbow',short:'A',billable:1,color:'#7c3aed'},
{id:'bElbow',label:'B Elbow',short:'B',billable:1,color:'#db2777'},
{id:'twoCrimp',label:'2-Crimp',short:'2C',billable:1,color:'#0891b2'},
{id:'fourCrimp',label:'4-Crimp',short:'4C',billable:1,color:'#9333ea'},
{id:'diverter',label:'Diverter',short:'D',billable:0,color:'#92400e'}
];
const $=id=>document.getElementById(id),toolById=id=>TOOLS.find(t=>t.id===id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0),num=id=>Number($(id).value||0),trim=n=>Number(Number(n).toFixed(2)).toString(),uid=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2);
let state={id:uid(),photos:[],selectedTool:'gutter',currentEntry:null};
$('jobDate').valueAsDate=new Date();
$('addPhotoBtn').onclick=()=>$('photoInput').click();
$('photoInput').onchange=async e=>{for(const file of [...e.target.files]){const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});state.photos.push({id:uid(),label:`Photo ${state.photos.length+1}`,dataUrl,markers:[],redo:[],view:{scale:1,x:0,y:0}})}e.target.value='';renderPhotos();calculate();dirty()};
function renderPhotos(){const root=$('photos');root.innerHTML='';if(!state.photos.length){root.innerHTML='<div class="note">No photos added yet.</div>';return}const tpl=$('photoCardTemplate');state.photos.forEach(photo=>{const node=tpl.content.firstElementChild.cloneNode(true),img=node.querySelector('.property-photo'),layer=node.querySelector('.marker-layer'),stage=node.querySelector('.canvas-stage'),viewport=node.querySelector('.canvas-viewport'),toolbar=node.querySelector('.toolbar'),shell=node.querySelector('.toolbar-shell'),summary=node.querySelector('.photo-summary'),label=node.querySelector('.photo-label');label.value=photo.label;label.oninput=()=>{photo.label=label.value;dirty()};img.src=photo.dataUrl;applyView(photo,stage);node.querySelector('.delete-photo').onclick=()=>{if(confirm('Delete this photo and all markers?')){state.photos=state.photos.filter(p=>p.id!==photo.id);renderPhotos();calculate();dirty()}};node.querySelector('.collapse-tools').onclick=e=>{shell.classList.toggle('collapsed');e.currentTarget.textContent=shell.classList.contains('collapsed')?'Show Tools':'Hide Tools'};TOOLS.forEach(t=>{const b=document.createElement('button');b.className='tool'+(state.selectedTool===t.id?' active':'');b.textContent=t.label;b.onclick=()=>{state.selectedTool=t.id;renderPhotos()};toolbar.appendChild(b)});node.querySelector('.undo').onclick=()=>undo(photo);node.querySelector('.redo').onclick=()=>redo(photo);node.querySelector('.reset-zoom').onclick=()=>{photo.view={scale:1,x:0,y:0};applyView(photo,stage)};installGestures(photo,viewport,stage,layer);photo.markers.forEach(m=>{const t=toolById(m.tool),el=document.createElement('button');el.className='marker';el.style.cssText=`left:${m.x}%;top:${m.y}%;background:${t.color}`;el.innerHTML=t.needsFeet?`${t.short}<span class="mini">${trim(m.value)}'</span>`:t.short;el.onclick=e=>{e.stopPropagation();openEntry(photo,m.x,m.y,m)};layer.appendChild(el)});const counts={};photo.markers.forEach(m=>counts[m.tool]=(counts[m.tool]||0)+1);summary.textContent=TOOLS.filter(t=>counts[t.id]).map(t=>`${t.label}: ${counts[t.id]}`).join(' • ')||'No measurements on this photo.';root.appendChild(node)})}
function applyView(photo,stage){const v=photo.view||{scale:1,x:0,y:0};stage.style.transform=`translate(${v.x}px,${v.y}px) scale(${v.scale})`}
function installGestures(photo,viewport,stage,layer){const pts=new Map();let startDist=0,startScale=1,startMid=null,startView=null,moved=false;viewport.onpointerdown=e=>{viewport.setPointerCapture(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=false;if(pts.size===2){const a=[...pts.values()];startDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);startScale=photo.view.scale;startMid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};startView={...photo.view}}};viewport.onpointermove=e=>{if(!pts.has(e.pointerId))return;const old=pts.get(e.pointerId);if(Math.hypot(old.x-e.clientX,old.y-e.clientY)>4)moved=true;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){e.preventDefault();const a=[...pts.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};photo.view.scale=Math.min(4,Math.max(1,startScale*(dist/startDist)));photo.view.x=startView.x+(mid.x-startMid.x);photo.view.y=startView.y+(mid.y-startMid.y);applyView(photo,stage)}};viewport.onpointerup=e=>{const wasTwo=pts.size>1;pts.delete(e.pointerId);if(!wasTwo&&!moved){const r=layer.getBoundingClientRect(),v=photo.view;const x=((e.clientX-r.left)/r.width)*100,y=((e.clientY-r.top)/r.height)*100;if(x>=0&&x<=100&&y>=0&&y<=100)openEntry(photo,x,y,null)} };viewport.onpointercancel=e=>pts.delete(e.pointerId)}
function openEntry(photo,x,y,existing){const t=existing?toolById(existing.tool):toolById(state.selectedTool);state.currentEntry={photoId:photo.id,x,y,existingId:existing?.id||null,tool:t.id};$('popoverTitle').textContent=(existing?'Edit ':'Add ')+t.label;$('measurementLabel').classList.toggle('hidden',!t.needsFeet);$('measurementInput').value=existing?.value??'';$('deleteEntry').classList.toggle('hidden',!existing);$('entryPopover').classList.remove('hidden');if(t.needsFeet)setTimeout(()=>$('measurementInput').focus(),50)}
$('cancelEntry').onclick=closeEntry;function closeEntry(){$('entryPopover').classList.add('hidden');state.currentEntry=null}
$('saveEntry').onclick=()=>{const e=state.currentEntry,p=state.photos.find(p=>p.id===e.photoId),t=toolById(e.tool),value=t.needsFeet?Number($('measurementInput').value):1;if(t.needsFeet&&!(value>0))return alert('Enter the footage.');if(e.existingId){const m=p.markers.find(m=>m.id===e.existingId);Object.assign(m,{value})}else p.markers.push({id:uid(),tool:e.tool,x:e.x,y:e.y,value});p.redo=[];closeEntry();renderPhotos();calculate();dirty()};
$('deleteEntry').onclick=()=>{const e=state.currentEntry,p=state.photos.find(p=>p.id===e.photoId);p.markers=p.markers.filter(m=>m.id!==e.existingId);p.redo=[];closeEntry();renderPhotos();calculate();dirty()};
function undo(p){const m=p.markers.pop();if(m){p.redo=p.redo||[];p.redo.push(m);renderPhotos();calculate();dirty()}}function redo(p){const m=(p.redo||[]).pop();if(m){p.markers.push(m);renderPhotos();calculate();dirty()}}
function aggregate(){const totals=Object.fromEntries(TOOLS.map(t=>[t.id,{count:0,feet:0}]));state.photos.forEach(p=>p.markers.forEach(m=>{totals[m.tool].count++;if(toolById(m.tool).needsFeet)totals[m.tool].feet+=Number(m.value||0)}));return totals}
function calculate(){const totals=aggregate();let billable=0;TOOLS.forEach(t=>billable+=t.needsFeet?totals[t.id].feet:totals[t.id].count*t.billable);const base=billable*num('pricePerFoot'),customer=Math.max(0,base+num('customerExtra')-num('customerDiscount')),costs=num('materials')+num('labor')+num('delivery')+num('otherCosts');$('billableFeet').textContent=trim(billable)+' ft';$('customerPrice').textContent=money(customer);$('totalCosts').textContent=money(costs);$('grossProfit').textContent=money(customer-costs);$('totalsGrid').innerHTML=TOOLS.map(t=>`<div class="total-box"><span>${t.label}</span><strong>${t.needsFeet?trim(totals[t.id].feet)+' ft':totals[t.id].count}</strong></div>`).join('')}
['jobName','jobDate','address','phone','notes','gutterStyle','downspoutStyle','pricePerFoot','customerExtra','customerDiscount','materials','labor','delivery','otherCosts'].forEach(id=>$(id).addEventListener('input',()=>{calculate();dirty()}));function dirty(){$('saveStatus').textContent='Unsaved'}
function collect(){return{id:state.id,photos:state.photos,job:{name:$('jobName').value,date:$('jobDate').value,address:$('address').value,phone:$('phone').value,notes:$('notes').value,gutterStyle:$('gutterStyle').value,downspoutStyle:$('downspoutStyle').value},pricing:Object.fromEntries(['pricePerFoot','customerExtra','customerDiscount','materials','labor','delivery','otherCosts'].map(k=>[k,num(k)]))}}
$('saveJobBtn').onclick=()=>{const jobs=JSON.parse(localStorage.getItem('snrGutterJobsV2')||'[]'),d=collect(),i=jobs.findIndex(j=>j.id===d.id);i>=0?jobs[i]=d:jobs.unshift(d);localStorage.setItem('snrGutterJobsV2',JSON.stringify(jobs));$('saveStatus').textContent='Saved';renderSavedJobs()};
function renderSavedJobs(){const jobs=JSON.parse(localStorage.getItem('snrGutterJobsV2')||'[]'),root=$('savedJobs');root.innerHTML=jobs.length?'':'<div class="note">No saved jobs yet.</div>';jobs.forEach(j=>{const row=document.createElement('div');row.className='saved-job';row.innerHTML=`<div><strong>${j.job?.name||'Untitled Job'}</strong><small>${j.job?.address||''}</small></div><button>Open</button>`;row.querySelector('button').onclick=()=>loadJob(j);root.appendChild(row)})}
function loadJob(j){state={id:j.id,photos:j.photos||[],selectedTool:'gutter',currentEntry:null};for(const [k,v] of Object.entries(j.job||{})){const map={name:'jobName',date:'jobDate',address:'address',phone:'phone',notes:'notes',gutterStyle:'gutterStyle',downspoutStyle:'downspoutStyle'};if(map[k]&&$(map[k]))$(map[k]).value=v??''}for(const [k,v] of Object.entries(j.pricing||{}))if($(k))$(k).value=v;renderPhotos();calculate();$('saveStatus').textContent='Saved';scrollTo({top:0,behavior:'smooth'})}
$('newJobBtn').onclick=()=>{if(confirm('Start a new blank job?'))location.reload()};$('printBtn').onclick=()=>window.print();renderPhotos();renderSavedJobs();calculate();
